// Every text the skill writes onto the Figma canvas (cover, Foundations boards, Components cards,
// Screens headers, the User flows map), in each documentation language. The language comes from
// the project's state.json (options.docsLanguage, set from the user's config); English when unset.
//
// Figma templates (figma/*.js) cannot import this module: the generators (sync.mjs, audit.mjs,
// gen-*.mjs) resolve the strings here and pass them in each template's PARAMS. Names that the
// audit compares with what a template created (foundation topics, the icons board) come from the
// same dictionary on both sides.
//
// Strings with {placeholders} are filled by the template or generator (fmt below); functions are
// resolved in Node before anything reaches Figma.
//
// Layer markers that the pipeline itself searches for (slot names "Rows", "Content", "Cell N",
// " (previous)", " · unchanged", " · no component") are fixed identifiers, not labels.

export const fmt = (s, o) => String(s).replace(/\{(\w+)\}/g, (m, k) => (o[k] === undefined ? m : o[k]));
const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;

const en = {
  lang: 'en',
  decimal: '.',
  dateLocale: 'en-CA', // YYYY-MM-DD
  parkPage: 'Previous components (temporary)',
  inbox: 'New screens',
  // the boards of the Components page, in this order (SKILL.md, step 1); other names go after
  stages: ['App structure', 'Navigation', 'Actions', 'Forms and search', 'Tables and lists', 'Sections and cards',
    'Charts and timelines', 'Status and feedback', 'Menus and overlays', 'Notices and detail', 'Chat', 'Identity'],
  iconsBoard: { name: 'Icons', desc: "The prototype's glyphs as components" },
  usesOnScreens: (uses, screens) => `${plural(uses, 'use', 'uses')} on ${plural(screens, 'screen', 'screens')}`,
  boardDesc: { modes: "Light and dark mode, bound to the file's variables", single: "Bound to the file's variables" },
  screens: {
    groupSub: (n, dark = true) => `${plural(n, 'screen', 'screens')}${dark ? ' · each with its dark version below' : ''}`,
    darkSuffix: ' · dark',
  },
  organize: {
    kind: { atom: 'Atom', component: 'Component', list: 'List · slot Rows', container: 'Container · slot Content' },
    anatomy: 'Anatomy', more: '… {n} more', instanceTag: ' (component)', textTag: ' (text)',
    specs: 'Specs', fixedPositions: 'Fixed positions (no auto layout)', textProp: 'text', radius: 'Radius', mixed: 'mixed',
    tokens: 'Tokens', color: 'Color', text: 'Text', space: 'Space',
    raw: 'No token: {fills} fills, {texts} texts', noRaw: 'No raw values',
    componentOne: 'component', componentMany: 'components', icons: '{n} icons', variantOne: 'variant', variantMany: 'variants',
    uses: '{n} uses on the screens', unused: 'not used on any screen',
  },
  cover: {
    section: 'Cover', content: 'content', facts: 'facts',
    platform: 'Platform', themes: 'Themes', themesNote: ' (modes of the Tokens collection)', contents: 'Contents',
    screens: (n) => plural(n, 'screen', 'screens'), components: (n) => plural(n, 'component', 'components'), flows: (n) => plural(n, 'flow', 'flows'),
    source: 'Source', generated: 'Generated',
    legend: {
      foundations: 'One board per topic (color, typography, spacing, layout and grid, iconography, elevation, borders and radii), in light and dark, taken from what the prototype really uses. The variables have light and dark modes and every token carries its var(--css).',
      components: 'Every component of the prototype, from atoms to containers (sidebar, header, panels), on one board per stage. Variants by props and structure; tables and lists keep their rows in the slot "Rows" and containers what changes in "Content". Each card gives the kind, the variants, the uses and the source class.',
      screens: 'One section per app. Every screen, made of instances, with its dark version below. The prototype starts at each flow\'s starting point.',
      flows: 'The map: one band per flow with each screen in light and dark and the gesture that leads to the next, grouped by app, and the compact map of each app.',
    },
    howToRead: 'How to read this file', index: 'Screen index', inFigma: '{done} of {n} in Figma', pending: 'Waiting for its capture', glossary: 'Glossary',
  },
  flowmap: {
    headSection: 'Flow map · how to read it', defaultName: 'Flow map',
    legend: [
      'A band is a flow: something a person does from start to finish. Bands are grouped by app.',
      'Each band has two rows: light on top and dark below, with the same screens.',
      'The arrow names the gesture that leads to the next screen.',
      'A fan is a screen that opens several: the parent on the left, the ones it opens in a column.',
      'Every screen has a stable code in its frame name: F4·3 = the third screen of band F4.',
      'These are the real designs (vectors, instances of the components), copied from the Screens page.',
      'On the right is the compact map: each app with its root and its sections, at a glance.',
    ],
    howToRead: 'How to read it', index: 'Index', indexLayer: 'index', screensCount: '{n} screens',
    colorTab: 'color tab', title: 'title', note: 'note', light: 'LIGHT', dark: 'DARK', themeLight: 'theme · light', themeDark: 'theme · dark',
    label: 'label', missing: 'Missing on Screens: {screen}', subtitle: 'subtitle', darkSuffix: ' · dark', gesture: 'gesture',
    compact: 'Compact', question: 'note', root: 'root', trunk: 'trunk', spine: 'spine',
  },
  foundations: {
    topics: { color: 'Color', type: 'Typography', space: 'Spacing', layout: 'Layout and grid', icons: 'Iconography', elevation: 'Elevation', borders: 'Borders and radii' },
    pairSample: 'Aa Text', specimen: 'Quarterly report 2026',
    // color
    semantic: { error: 'Error', warning: 'Warning', success: 'Success', info: 'Info' },
    cats: { brand: 'Apps and brand', shadow: 'Shadow', semantic: 'Semantic', text: 'Text and icons', borders: 'Borders', states: 'States', surfaces: 'Backgrounds and surfaces' },
    catNote: {
      surfaces: 'Layers of the interface, from the base to what is raised.',
      text: 'Ink on backgrounds. fg for content, muted for support.',
      borders: 'Dividers and outlines of surfaces.',
      states: 'Hover, pressed, selected and focus.',
      semantic: 'Fixed meaning: error, warning, success, info.',
      brand: 'Identity color of each app. The same in light and dark.',
      shadow: 'Shadow color; Elevation documents the depth.',
    },
    levels: { aaa: 'AAA', aa: 'AA', aaLarge: 'AA large', aaUi: 'AA (UI)', fail: 'Fail' },
    colorSub: (n) => `${n} tokens with light and dark mode, grouped by use. Every swatch is bound to its variable: changing the token changes this page and every screen.`,
    semanticTitle: 'Semantic colors', semanticSub: 'Each meaning needs a soft background and a legible ink on it.',
    semanticHead: ['Meaning', 'Background', 'Ink / accent', 'Status'],
    semanticGap: { none: 'Missing: no token for this meaning', soft: 'Missing the soft background', ink: 'Missing the ink', ok: 'Complete' },
    checkSemantic: (role) => `Semantic ${role}`,
    semanticNote: { ok: 'background and ink', none: 'does not exist', soft: 'no soft background', ink: 'no ink' },
    contrastTitle: 'Contrast (WCAG 2.2)',
    contrastSub: 'Normal text: AA 4.5:1, AAA 7:1. Large text (≥ 18 px, or ≥ 14 px bold): AA 3:1. Non-text elements (UI): 3:1. Computed in each mode.',
    contrastHead: ['Pair (ink on background)', 'Sample', 'Ratio', 'Level', 'Use'],
    useText: 'Text', useIndicator: 'Indicator (not text)',
    checkPalette: 'Palette by use (backgrounds, text, borders, states)',
    checkContrast: 'WCAG contrast: text pairs at AA',
    contrastNote: (n, f) => `${n} pairs; ${f} under AA in some mode`,
    checkPrimitives: 'Primitives separate from tokens', primitivesNote: 'Primitives collection (hidden) + Tokens with aliases',
    // type
    typeSub: (frames, n, pct) => `Scale taken from the ${frames} screens: ${n} text styles that cover ${pct} % of the texts. Each style exists in Figma (styles panel) with its line height and tracking.`,
    family: 'Family', familyHead: ['Family', 'Sample', 'Weights in use'], familySample: 'Aa Bb Cc 0123456789 ¿¡ñ€$',
    headingsTitle: 'Headings h1–h6', headingsSub: 'Hierarchy of the titles in use, from the largest to the smallest.',
    headingsHead: ['Level', 'Sample', 'Style', 'Size / line · weight'], headingSample: 'Project overview',
    scaleTitle: 'Full scale', scaleSub: 'Size, weight, line height (normal ≈ 145 %, tight ≈ 130 %) and tracking of each style, with its frequency.',
    scaleHead: ['Style', 'Sample', 'Size / line · weight', 'Tracking', 'Uses'], upperSample: 'Section label', bodySample: 'The quick brown fox jumps over the lazy dog',
    styleDesc: (n, size, lh, w, ls) => `${n} uses on screens · ${size}/${lh} px · ${w} · tracking ${ls} px`,
    outliers: (min, list) => `Off the scale (fewer than ${min} uses, no style of their own): ${list}. Better moved to the nearest style.`,
    checkCensus: 'Text census', censusMissing: 'type-census.json is missing: run figma/census-type.js',
    checkFamilies: 'Families', checkSizes: 'Size scale', checkWeights: 'Weights', checkLineHeight: 'Line height', lineHeightNote: 'fixed in px per style (normal and tight)',
    checkTracking: 'Letter spacing', trackingNote: (n) => `${n} styles with tracking ≠ 0`,
    checkStyles: 'Defined styles (h1–h6, body, caption…)', stylesNote: (n, h) => `${n} styles · h1–h6: ${h}`,
    checkCoverage: 'Text coverage by styles', coverageNote: (pct, n) => `${pct} % · ${n} looks off the scale`,
    // spacing
    spaceVarDesc: (s, n) => `${s} px · ${n} uses in the CSS. Proposed: the prototype uses the literal value, not a CSS variable.`,
    dimNote: { '--row': 'List row height', '--pad': 'Base panel padding', '--rail-w': 'Sidebar width (expanded)', '--rail-min': 'Sidebar width (collapsed)', '--pane-w': 'Side panel width', '--sbw': 'Scrollbar width' },
    density: { compact: 'compact', medium: 'medium', comfortable: 'comfortable', none: 'no data' },
    spaceSub: (n, pct) => `Base-4 scale with half steps, taken from ${n} gap, padding and margin values in the CSS. The scale covers ${pct} % of them. The space/* variables are scoped to Gap (auto layout spacing and padding).`,
    scale: 'Scale', spaceHead: ['Token', 'Value', 'Sample', 'Uses in CSS'],
    offScale: (list) => `Off the scale: ${list}. Better rounded to the nearest step.`, allInScale: 'Every value falls on the scale.',
    densityTitle: 'Density and layout measures', densitySub: (d, row) => `Density ${d}: row of ${row} px. These measures are tokens of the prototype (size/*).`,
    densityHead: ['Token', 'Value', 'CSS', 'Use'],
    checkSpaceScale: 'Consistent scale (base 4)', checkSpaceTokens: 'Margin/padding tokens', spaceTokensNote: (n) => `${n} space/* variables (Gap scope)`,
    checkSpaceCoverage: 'CSS coverage by the scale', spaceCoverageNote: (pct, list) => `${pct} % · off: ${list}`,
    checkDensity: 'Density', densityNote: (d, row, pad) => `${d} (row ${row} px, padding ${pad})`,
    // layout
    grid: { open: 'Layout/Shell · sidebar open', closed: 'Layout/Shell · sidebar collapsed', panel: 'Layout/Shell · with panel', base: 'Layout/Base 4' },
    gridDesc: { open: (w) => `Sidebar of ${w} px and fluid content`, closed: (w) => `Sidebar of ${w} px and fluid content`, panel: (w, p) => `Sidebar ${w} px, content, panel ${p} px`, base: '4 px grid to align and space' },
    layoutSub: (w, h, shell) => `Frame of ${w}×${h}.${shell ? ' The structure is a shell of columns (sidebar, content, panel), not a 12-column grid.' : ''} The Layout/* grid styles exist in Figma to apply to a frame.`,
    shell: 'Shell', shellSub: 'Columns of the application to scale.',
    seg: { rail: 'Sidebar', content: 'Content', panel: 'Panel', railNote: (w, m) => `${w} px · collapsed ${m} px`, contentNote: 'fluid · minmax(0, 1fr)' },
    shellCaption: (pad) => `grid-template-columns: var(--rail-w) minmax(0, 1fr) · with panel: minmax(0, 1fr) 8px var(--pane-w). Base panel padding: ${pad} px.`,
    breakpoints: 'Breakpoints', bpHead: ['Name', 'Width', 'What changes'], desktop: 'Desktop', desktopNote: 'Base design of every screen',
    compactBp: 'Compact', compactNote: (q) => `Rules under @media (${q})`, tablet: 'Tablet / mobile', tabletNote: 'Not defined in the prototype',
    containers: 'Containers and text measure', containersHead: ['Container', 'Maximum', 'Use'], runningText: 'Running text', readable: 'Readable line length',
    patterns: 'Column patterns', patternsSub: 'Most used grid-template-columns declarations.', patternsHead: ['Pattern', 'Uses'],
    gridStyles: 'Grid styles in Figma', gridStylesHead: ['Style', 'Description'],
    checkShell: 'Columns / shell', shellNote: (w, m, p) => `sidebar ${w}/${m}, panel ${p}, fluid content`, shellNone: 'no sidebar/panel shell tokens (--rail-w, --pane-w): the layout is the frame itself',
    checkBreakpoints: 'Responsive breakpoints', bpNote: (n, list) => `${n} breakpoint (${list} px); no tablet or mobile`, none: 'none',
    checkContainers: 'Containers and page margins', containersNote: (c, m, pad) => `${c} containers, ${m} text measures, padding ${pad} px`,
    checkGridStyles: 'Grid styles',
    // icons
    iconSub: (glyphs, sets) => `${glyphs} glyphs in ${sets} sets, drawn on a 24 grid. The color is always currentColor: the icon takes the color of the text it goes with.`,
    setsTitle: 'Sets and style', setsHead: ['Set', 'Glyphs', 'Grid', 'Stroke', 'Use'], line: 'Line', solid: 'Solid',
    strokeNote: (w, caps) => `${w} px · ${caps} caps`, solidNote: 'Fill, no stroke',
    lineUse: 'Interface controls (search, close, send…)', solidUse: 'Objects and states (apps, inbox, check…)',
    sizesTitle: 'Sizes in use', sizesSub: 'The icon scales with CSS; the stroke scales with it.', sizesHead: ['Size', 'Where'],
    rulesTitle: 'Usage rules', rulesHead: ['Rule', 'Detail'],
    ruleColor: 'Color', ruleColorText: (def, states) => `Inherits currentColor. By default ${def}; states use their semantic ink (${states}).`, textColor: 'the color of the text',
    ruleLineSolid: 'Line vs solid', ruleLineSolidText: 'Line for interface actions; solid for objects and states. Do not mix the two in one group of buttons.',
    ruleSize: 'Size', ruleSizeText: 'The icon goes with the body text: 13–15 px next to 12–13.5 px text; 16 px in toolbars.',
    ruleA11y: 'Accessibility', ruleA11yText: 'Decorative: aria-hidden. A button with only an icon needs an aria-label.',
    galleryTitle: 'Icon components', gallerySub: 'Instances of each Icon/* component at 24 px. In red, the ones without a name.',
    checkIconStyle: 'Style (grid, stroke, fill)', iconStyleNote: (line, n, vb, stroke) => `${line ? 'line' : 'solid'} ${n} (${vb})${stroke ? ' stroke ' + stroke : ''}`,
    checkIconSizes: 'Size scale', iconSizesNote: (n, list) => `${n} sizes: ${list} px`, checkIconRules: 'Usage rules', iconRulesNote: 'color, set, size, accessibility',
    // elevation
    elevNote: { '.pop': 'Popovers and menus', '.popover': 'Popovers', '.menu': 'Menus', '.dropdown': 'Dropdowns', '.tooltip': 'Tooltips', '.modal': 'Dialogs', '.dialog': 'Dialogs' },
    ring: { selected: 'Ring/Selected', off: 'Ring/Off', cutout: 'Ring/Cutout', focus: 'Ring/Focus' },
    ringNote: { selected: 'Current card or mark (aria-current)', off: 'Hollow status dot (off, no data)', cutout: 'Separates a badge from the background' },
    focusNote: (v, off) => `Keyboard focus · outline: ${v}; outline-offset ${off}px`,
    elevTitle: 'Elevation and shadows',
    elevSub: 'Depth by levels. The interface is flat: almost everything is separated with background and border, and the shadow is kept for what floats. The effect styles are bound to the shadow tokens, so they change with the mode.',
    levels2: 'Levels', level0: 'Level 0 · flat', level0Note: 'Cards and panels: background + border, no shadow.', levelN: 'Level ',
    rings: 'Rings', ringsSub: 'Outlines made with a spread shadow: they do not move the layout.',
    elevHead: ['Style', 'Value', 'Use'],
    checkLevels: 'Depth levels', checkEffects: 'Effect styles', checkFocus: 'Visible focus',
    focusCountNote: (n) => `focus outline in ${n} places (keyboard only); the rest use :focus { outline: none }`,
    // borders
    bordersSub: (tok, circles, raw, styles) => `Radii by token: ${tok} uses of var(--r-*), ${circles} circles (50 %) and ${raw} raw values. Borders ${styles}.`,
    radii: 'Radii', circle: 'Circle', circleNote: '50 % · avatars and dots',
    rawRadii: (list) => `Raw values: ${list}.`, allRadiiTokens: 'Every radius uses a token.',
    widths: 'Widths', widthsSub: 'border/* variables (stroke width scope).', widthNote: (w, n) => `${w} px · ${n} CSS borders`, widthDesc: (w) => `Border width ${w} px`,
    borderColors: 'Border colors',
    checkRadii: 'Radii with token', radiiNote: (t, c, r) => `${t} with token, ${c} circles, ${r} raw`,
    checkWidths: 'Widths', checkBorderStyles: 'Border styles',
  },
};

const es = {
  lang: 'es',
  decimal: ',',
  dateLocale: 'es', // DD/MM/YYYY
  parkPage: 'Componentes anteriores (temporal)',
  inbox: 'Pantallas nuevas',
  stages: ['Estructura de la app', 'Navegación', 'Acciones', 'Formularios y búsqueda', 'Tablas y listas', 'Secciones y tarjetas',
    'Gráficos y líneas de tiempo', 'Estado y feedback', 'Menús y superposiciones', 'Avisos y detalle', 'Chat', 'Identidad'],
  iconsBoard: { name: 'Íconos', desc: 'Los glifos del prototipo como componentes' },
  usesOnScreens: (uses, screens) => `${uses} usos en ${plural(screens, 'pantalla', 'pantallas')}`,
  boardDesc: { modes: 'Modo claro y oscuro, ligados a las variables del archivo', single: 'Ligado a las variables del archivo' },
  screens: {
    groupSub: (n, dark = true) => `${plural(n, 'pantalla', 'pantallas')}${dark ? ' · cada una con su versión oscura debajo' : ''}`,
    darkSuffix: ' · oscuro',
  },
  organize: {
    kind: { atom: 'Átomo', component: 'Componente', list: 'Lista · slot Rows', container: 'Contenedor · slot Content' },
    anatomy: 'Anatomía', more: '… {n} más', instanceTag: ' (componente)', textTag: ' (texto)',
    specs: 'Specs', fixedPositions: 'Posiciones fijas (sin auto layout)', textProp: 'texto', radius: 'Radio', mixed: 'mixto',
    tokens: 'Tokens', color: 'Color', text: 'Texto', space: 'Espacio',
    raw: 'Sin token: {fills} rellenos, {texts} textos', noRaw: 'Sin valores sueltos',
    componentOne: 'componente', componentMany: 'componentes', icons: '{n} íconos', variantOne: 'variante', variantMany: 'variantes',
    uses: '{n} usos en las pantallas', unused: 'sin uso en las pantallas',
  },
  cover: {
    section: 'Portada', content: 'contenido', facts: 'datos',
    platform: 'Plataforma', themes: 'Temas', themesNote: ' (modos de la colección Tokens)', contents: 'Contenido',
    screens: (n) => plural(n, 'pantalla', 'pantallas'), components: (n) => plural(n, 'componente', 'componentes'), flows: (n) => plural(n, 'flujo', 'flujos'),
    source: 'Fuente', generated: 'Generado',
    legend: {
      foundations: 'Un tablero por tema —color, tipografía, espaciado, layout y grid, iconografía, elevación, bordes y radios—, en claro y oscuro, sacado de lo que el prototipo usa de verdad. Las variables tienen modo claro y oscuro y cada token lleva su var(--css).',
      components: 'Todos los componentes del prototipo, de los átomos a los contenedores (barra lateral, encabezado, paneles), en un tablero por etapa. Variantes por props y estructura; las tablas y listas guardan sus filas en el slot «Rows» y los contenedores lo que cambia en «Content». Cada tarjeta dice el tipo, las variantes, los usos y la clase de origen.',
      screens: 'Una sección por app. Cada pantalla, hecha de instancias, con su versión oscura debajo. El prototipo arranca en el punto de inicio de cada flujo.',
      flows: 'El mapa: una banda por flujo con cada pantalla en claro y oscuro y el gesto que lleva a la siguiente, agrupadas por app, y el mapa compacto de cada app.',
    },
    howToRead: 'Cómo leer este archivo', index: 'Índice de pantallas', inFigma: '{done} de {n} en Figma', pending: 'Pendiente de captura', glossary: 'Glosario',
  },
  flowmap: {
    headSection: 'Mapa de flujos · cómo se lee', defaultName: 'Mapa de flujos',
    legend: [
      'Una banda es un flujo: algo que alguien hace de principio a fin. Las bandas están agrupadas por app.',
      'Cada banda tiene dos filas: claro arriba y oscuro abajo, con las mismas pantallas.',
      'La flecha dice el gesto que lleva a la siguiente pantalla.',
      'Un abanico es una pantalla que abre varias: el padre a la izquierda, las que abre en columna.',
      'Cada pantalla tiene un código estable, F4·3 = la tercera de la banda F4, en el nombre del marco.',
      'Son los diseños reales (vectores, instancias de los componentes), copiados de la página Screens.',
      'A la derecha está el mapa compacto: cada app con su raíz y sus secciones, en una mirada.',
    ],
    howToRead: 'Cómo se lee', index: 'Índice', indexLayer: 'índice', screensCount: '{n} pantallas',
    colorTab: 'tejuelo', title: 'título', note: 'nota', light: 'CLARO', dark: 'OSCURO', themeLight: 'tema · claro', themeDark: 'tema · oscuro',
    label: 'rótulo', missing: 'Falta en Screens: {screen}', subtitle: 'bajada', darkSuffix: ' · oscuro', gesture: 'gesto',
    compact: 'Compacto', question: 'pregunta', root: 'raíz', trunk: 'tronco', spine: 'espina',
  },
  foundations: {
    topics: { color: 'Color', type: 'Tipografía', space: 'Espaciado', layout: 'Layout y grid', icons: 'Iconografía', elevation: 'Elevación', borders: 'Bordes y radios' },
    pairSample: 'Aa Texto', specimen: 'Informe trimestral 2026',
    semantic: { error: 'Error', warning: 'Advertencia', success: 'Éxito', info: 'Información' },
    cats: { brand: 'Apps y marca', shadow: 'Sombra', semantic: 'Semánticos', text: 'Texto e íconos', borders: 'Bordes', states: 'Estados', surfaces: 'Fondos y superficies' },
    catNote: {
      surfaces: 'Capas de la interfaz, de la base a lo elevado.',
      text: 'Tinta sobre fondos. fg para contenido, muted para apoyo.',
      borders: 'Divisores y contornos de superficies.',
      states: 'Hover, presionado, seleccionado y foco.',
      semantic: 'Significado fijo: error, advertencia, éxito, información.',
      brand: 'Color de identidad de cada app. Igual en claro y oscuro.',
      shadow: 'Color de sombra; la elevación la documenta Elevación.',
    },
    levels: { aaa: 'AAA', aa: 'AA', aaLarge: 'AA grande', aaUi: 'AA (UI)', fail: 'Falla' },
    colorSub: (n) => `${n} tokens con modo claro y oscuro, agrupados por uso. Cada muestra está ligada a su variable: cambiar el token cambia esta página y todas las pantallas.`,
    semanticTitle: 'Colores semánticos', semanticSub: 'Cada significado necesita un fondo suave y una tinta legible sobre él.',
    semanticHead: ['Significado', 'Fondo', 'Tinta / acento', 'Estado'],
    semanticGap: { none: 'Falta: no hay token para este significado', soft: 'Falta el fondo suave', ink: 'Falta la tinta', ok: 'Completo' },
    checkSemantic: (role) => `Semántico ${role}`,
    semanticNote: { ok: 'fondo y tinta', none: 'no existe', soft: 'sin fondo suave', ink: 'sin tinta' },
    contrastTitle: 'Contraste (WCAG 2.2)',
    contrastSub: 'Texto normal: AA 4,5:1, AAA 7:1. Texto grande (≥ 18 px, o ≥ 14 px en negrita): AA 3:1. Elementos no textuales (UI): 3:1. Se calcula en cada modo.',
    contrastHead: ['Par (tinta sobre fondo)', 'Muestra', 'Relación', 'Nivel', 'Uso'],
    useText: 'Texto', useIndicator: 'Indicador (no texto)',
    checkPalette: 'Paleta por uso (fondos, texto, bordes, estados)',
    checkContrast: 'Contraste WCAG: pares de texto en AA',
    contrastNote: (n, f) => `${n} pares; ${f} bajo AA en algún modo`,
    checkPrimitives: 'Primitivas separadas de tokens', primitivesNote: 'colección Primitives (oculta) + Tokens con alias',
    typeSub: (frames, n, pct) => `Escala sacada de las ${frames} pantallas: ${n} estilos de texto que cubren ${pct} % de los textos. Cada estilo existe en Figma (panel de estilos) con su altura de línea y tracking.`,
    family: 'Familia', familyHead: ['Familia', 'Muestra', 'Pesos en uso'], familySample: 'Aa Bb Cc 0123456789 ¿¡ñ€$',
    headingsTitle: 'Encabezados h1–h6', headingsSub: 'Jerarquía de títulos en uso, del más grande al más chico.',
    headingsHead: ['Nivel', 'Muestra', 'Estilo', 'Tamaño / línea · peso'], headingSample: 'Resumen del proyecto',
    scaleTitle: 'Escala completa', scaleSub: 'Tamaño, peso, altura de línea (normal ≈ 145 %, tight ≈ 130 %) y tracking de cada estilo, con su frecuencia.',
    scaleHead: ['Estilo', 'Muestra', 'Tamaño / línea · peso', 'Tracking', 'Usos'], upperSample: 'Etiqueta de sección', bodySample: 'El veloz murciélago hindú comía feliz cardillo y kiwi',
    styleDesc: (n, size, lh, w, ls) => `${n} usos en pantallas · ${size}/${lh} px · ${w} · tracking ${ls} px`,
    outliers: (min, list) => `Fuera de escala (menos de ${min} usos, sin estilo propio): ${list}. Conviene llevarlos al estilo más cercano.`,
    checkCensus: 'Censo de textos', censusMissing: 'falta type-census.json: correr figma/census-type.js',
    checkFamilies: 'Familias', checkSizes: 'Escala de tamaños', checkWeights: 'Pesos', checkLineHeight: 'Altura de línea', lineHeightNote: 'fija en px por estilo (normal y tight)',
    checkTracking: 'Espaciado entre letras', trackingNote: (n) => `${n} estilos con tracking ≠ 0`,
    checkStyles: 'Estilos definidos (h1–h6, body, caption…)', stylesNote: (n, h) => `${n} estilos · h1–h6: ${h}`,
    checkCoverage: 'Cobertura de textos por estilos', coverageNote: (pct, n) => `${pct} % · ${n} looks fuera de escala`,
    spaceVarDesc: (s, n) => `${s} px · ${n} usos en el CSS. Propuesto: el prototipo usa el valor literal, no una variable CSS.`,
    dimNote: { '--row': 'Alto de fila de lista', '--pad': 'Padding base de paneles', '--rail-w': 'Ancho de la barra lateral abierta', '--rail-min': 'Ancho de la barra lateral cerrada', '--pane-w': 'Ancho del panel lateral', '--sbw': 'Ancho de scrollbar' },
    density: { compact: 'compacta', medium: 'media', comfortable: 'cómoda', none: 'sin dato' },
    spaceSub: (n, pct) => `Escala base 4 con medios pasos, sacada de ${n} valores de gap, padding y margin del CSS. La escala cubre ${pct} % de ellos. Las variables space/* tienen alcance Gap (espacio y padding de auto layout).`,
    scale: 'Escala', spaceHead: ['Token', 'Valor', 'Muestra', 'Usos en CSS'],
    offScale: (list) => `Fuera de escala: ${list}. Conviene redondearlos al paso más cercano.`, allInScale: 'Todos los valores caen en la escala.',
    densityTitle: 'Densidad y medidas de layout', densitySub: (d, row) => `Densidad ${d}: fila de ${row} px. Estas medidas son tokens del prototipo (size/*).`,
    densityHead: ['Token', 'Valor', 'CSS', 'Uso'],
    checkSpaceScale: 'Escala consistente (base 4)', checkSpaceTokens: 'Tokens de margin/padding', spaceTokensNote: (n) => `${n} variables space/* (alcance Gap)`,
    checkSpaceCoverage: 'Cobertura del CSS por la escala', spaceCoverageNote: (pct, list) => `${pct} % · fuera: ${list}`,
    checkDensity: 'Densidad', densityNote: (d, row, pad) => `${d} (fila ${row} px, padding ${pad})`,
    grid: { open: 'Layout/Shell · barra abierta', closed: 'Layout/Shell · barra cerrada', panel: 'Layout/Shell · con panel', base: 'Layout/Base 4' },
    gridDesc: { open: (w) => `Barra lateral de ${w} px y contenido fluido`, closed: (w) => `Barra lateral de ${w} px y contenido fluido`, panel: (w, p) => `Barra ${w} px, contenido, panel ${p} px`, base: 'Retícula de 4 px para alinear y espaciar' },
    layoutSub: (w, h, shell) => `Marco de ${w}×${h}.${shell ? ' La estructura es un shell de columnas (barra lateral, contenido, panel), no una retícula de 12 columnas.' : ''} Los estilos de grid Layout/* existen en Figma para aplicarlos a un marco.`,
    shell: 'Shell', shellSub: 'Columnas de la aplicación a escala.',
    seg: { rail: 'Barra lateral', content: 'Contenido', panel: 'Panel', railNote: (w, m) => `${w} px · cerrada ${m} px`, contentNote: 'fluido · minmax(0, 1fr)' },
    shellCaption: (pad) => `grid-template-columns: var(--rail-w) minmax(0, 1fr) · con panel: minmax(0, 1fr) 8px var(--pane-w). Padding base de paneles: ${pad} px.`,
    breakpoints: 'Breakpoints', bpHead: ['Nombre', 'Ancho', 'Qué cambia'], desktop: 'Escritorio', desktopNote: 'Diseño base de todas las pantallas',
    compactBp: 'Compacto', compactNote: (q) => `Reglas dentro de @media (${q})`, tablet: 'Tableta / móvil', tabletNote: 'No definido en el prototipo',
    containers: 'Contenedores y medida de texto', containersHead: ['Contenedor', 'Máximo', 'Uso'], runningText: 'Texto corrido', readable: 'Largo de línea legible',
    patterns: 'Patrones de columnas', patternsSub: 'Declaraciones grid-template-columns más usadas.', patternsHead: ['Patrón', 'Usos'],
    gridStyles: 'Estilos de grid en Figma', gridStylesHead: ['Estilo', 'Descripción'],
    checkShell: 'Columnas / shell', shellNote: (w, m, p) => `barra ${w}/${m}, panel ${p}, contenido fluido`, shellNone: 'sin tokens de shell de barra/panel (--rail-w, --pane-w): el layout es el marco mismo',
    checkBreakpoints: 'Breakpoints responsive', bpNote: (n, list) => `${n} breakpoint (${list} px); sin tableta ni móvil`, none: 'ninguno',
    checkContainers: 'Contenedores y márgenes de página', containersNote: (c, m, pad) => `${c} contenedores, ${m} medidas de texto, padding ${pad} px`,
    checkGridStyles: 'Estilos de grid',
    iconSub: (glyphs, sets) => `${glyphs} glifos en ${sets} sets, dibujados en retícula de 24. El color siempre es currentColor: el ícono toma el color del texto que acompaña.`,
    setsTitle: 'Sets y estilo', setsHead: ['Set', 'Glifos', 'Retícula', 'Trazo', 'Uso'], line: 'Línea', solid: 'Sólido',
    strokeNote: (w, caps) => `${w} px · puntas ${caps}`, solidNote: 'Relleno, sin trazo',
    lineUse: 'Controles de la interfaz (buscar, cerrar, enviar…)', solidUse: 'Objetos y estados (apps, bandeja, check…)',
    sizesTitle: 'Tamaños en uso', sizesSub: 'El ícono se escala con CSS; el trazo escala con él.', sizesHead: ['Tamaño', 'Dónde'],
    rulesTitle: 'Reglas de uso', rulesHead: ['Regla', 'Detalle'],
    ruleColor: 'Color', ruleColorText: (def, states) => `Hereda currentColor. Por defecto ${def}; los estados usan su tinta semántica (${states}).`, textColor: 'el color del texto',
    ruleLineSolid: 'Línea vs sólido', ruleLineSolidText: 'Línea para acciones de la interfaz; sólido para objetos y estados. No mezclar los dos en un mismo grupo de botones.',
    ruleSize: 'Tamaño', ruleSizeText: 'El ícono acompaña el cuerpo del texto: 13–15 px junto a texto de 12–13,5 px; 16 px en barras de herramientas.',
    ruleA11y: 'Accesibilidad', ruleA11yText: 'Decorativo: aria-hidden. Un botón solo con ícono necesita aria-label.',
    galleryTitle: 'Componentes de ícono', gallerySub: 'Instancias de cada componente Icon/* a 24 px. En rojo, los que no tienen nombre.',
    checkIconStyle: 'Estilo (retícula, trazo, relleno)', iconStyleNote: (line, n, vb, stroke) => `${line ? 'línea' : 'sólido'} ${n} (${vb})${stroke ? ' trazo ' + stroke : ''}`,
    checkIconSizes: 'Escala de tamaños', iconSizesNote: (n, list) => `${n} tamaños: ${list} px`, checkIconRules: 'Reglas de uso', iconRulesNote: 'color, set, tamaño, accesibilidad',
    elevNote: { '.pop': 'Popovers y menús', '.popover': 'Popovers', '.menu': 'Menús', '.dropdown': 'Desplegables', '.tooltip': 'Tooltips', '.modal': 'Diálogos', '.dialog': 'Diálogos' },
    ring: { selected: 'Ring/Seleccionado', off: 'Ring/Apagado', cutout: 'Ring/Recorte', focus: 'Ring/Foco' },
    ringNote: { selected: 'Tarjeta o marca actual (aria-current)', off: 'Punto de estado hueco (off, sin dato)', cutout: 'Separa un distintivo del fondo' },
    focusNote: (v, off) => `Foco con teclado · outline: ${v}; outline-offset ${off}px`,
    elevTitle: 'Elevación y sombras',
    elevSub: 'Profundidad por niveles. La interfaz es plana: casi todo se separa con fondo y borde, y la sombra queda para lo que flota. Los estilos de efecto están ligados a los tokens de sombra, así que cambian con el modo.',
    levels2: 'Niveles', level0: 'Nivel 0 · plano', level0Note: 'Tarjetas y paneles: fondo + borde, sin sombra.', levelN: 'Nivel ',
    rings: 'Anillos', ringsSub: 'Contornos hechos con sombra de extensión: no mueven el layout.',
    elevHead: ['Estilo', 'Valor', 'Uso'],
    checkLevels: 'Niveles de profundidad', checkEffects: 'Estilos de efecto', checkFocus: 'Foco visible',
    focusCountNote: (n) => `outline de foco en ${n} lugares (solo con teclado); el resto usa :focus { outline: none }`,
    bordersSub: (tok, circles, raw, styles) => `Radios por token: ${tok} usos con var(--r-*), ${circles} círculos (50 %) y ${raw} valores sueltos. Bordes ${styles}.`,
    radii: 'Radios', circle: 'Círculo', circleNote: '50 % · avatares y puntos',
    rawRadii: (list) => `Valores sueltos: ${list}.`, allRadiiTokens: 'Todos los radios usan token.',
    widths: 'Grosores', widthsSub: 'Variables border/* (alcance grosor de trazo).', widthNote: (w, n) => `${w} px · ${n} bordes CSS`, widthDesc: (w) => `Grosor de borde ${w} px`,
    borderColors: 'Colores de borde',
    checkRadii: 'Radios con token', radiiNote: (t, c, r) => `${t} con token, ${c} círculos, ${r} sueltos`,
    checkWidths: 'Grosores', checkBorderStyles: 'Estilos de borde',
  },
};

export const LANGS = { en, es };

// The dictionary for a project: state.options.docsLanguage, English when unset.
export function labelsFor(state) {
  const lang = (state && state.options && state.options.docsLanguage) || 'en';
  if (!LANGS[lang]) throw new Error(`docsLanguage "${lang}" is not supported; use one of: ${Object.keys(LANGS).join(', ')}`);
  return LANGS[lang];
}

// The adapter's stages in board order: the known names first, in the canonical order of the
// docs language (either language's name is recognized), then any other name in adapter order.
export function orderStages(L, names) {
  const norm = (n) => String(n).trim().toLowerCase();
  const rank = (n) => {
    for (const lang of [L, ...Object.values(LANGS)]) { const i = lang.stages.map(norm).indexOf(norm(n)); if (i >= 0) return i; }
    return Infinity;
  };
  return [...new Set(names)].map((n, k) => [n, k]).sort((a, b) => (rank(a[0]) - rank(b[0])) || (a[1] - b[1])).map(([n]) => n);
}

// The foundation topics in board order: the names foundation-board.js gives the sections and the
// order audit.mjs expects on the Foundations page.
export const topicOrder = (L) => ['color', 'type', 'space', 'layout', 'icons', 'elevation', 'borders'].map((k) => L.foundations.topics[k]);
