#!/usr/bin/env node
// Generates the use_figma script for the Cover page, in the house style of the documentation
// pages (#cacaca canvas, one #bdbdbd section, fixed inks that pass AA on the gray): product
// summary, source fingerprint, how to read the file, the screen index (every screen links to its
// frame) and the glossary. The User flows page is gen-flowmap.mjs.
//
//   node gen-docs.mjs <map-dir> <state.json> <out-dir> [--date <text>]   → <out-dir>/cover.figma.js
//
// The texts come from the project's docs language (lib/labels.mjs); the date is today's, in the
// local time zone and the language's date format, unless --date gives it.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { labelsFor } from './lib/labels.mjs';

const args = process.argv.slice(2);
const [mapDir, stateFile, outDir] = args;
const opt = (k, d) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : d; };
const state = JSON.parse(readFileSync(stateFile, 'utf8'));
const manifest = JSON.parse(readFileSync(path.join(mapDir, 'manifest.json'), 'utf8'));
const LL = labelsFor(state);
const L = LL.cover;
const date = opt('--date', new Date().toLocaleDateString(LL.dateLocale, { day: '2-digit', month: '2-digit', year: 'numeric' }));
// the legend names each documentation page as the project calls it (config pageNames)
const PN = { foundations: 'Foundations', components: 'Components', screens: 'Screens', flows: 'User flows', ...(state.pageNames || {}) };
const ST = state.style || { pageBg: '#cacaca', sectionFill: '#bdbdbd', title: '#1a1c1f', subtle: '#3d3f42', gap: 200 };
const adapterFile = state.adapter && path.join(path.dirname(stateFile), state.adapter);
const components = adapterFile && existsSync(adapterFile) ? JSON.parse(readFileSync(adapterFile, 'utf8')).components.length : null;
const frameOf = (s) => (state.screens[s] || {}).frame || null;
const titleOf = (s) => (manifest.screens[s] || {}).title || s;
mkdirSync(outDir, { recursive: true });

const DATA = {
  page: state.pages.cover, style: ST, name: manifest.name, summary: manifest.summary, date,
  facts: [
    [L.platform, manifest.platform + ' · ' + manifest.device.join(' × ')],
    [L.themes, manifest.themes.join(' · ') + L.themesNote],
    [L.contents, [L.screens(Object.keys(state.screens).length), components && L.components(components),
      L.flows(manifest.flows.length)].filter(Boolean).join(' · ')],
    [L.source, manifest.source.file + ' · sha256 ' + manifest.source.sha256.slice(0, 16) + '…'],
    [L.generated, date],
  ],
  legend: [
    [PN.foundations, L.legend.foundations],
    [PN.components, L.legend.components],
    [PN.screens, L.legend.screens],
    [PN.flows, L.legend.flows],
  ],
  text: { section: L.section, content: L.content, facts: L.facts, howToRead: L.howToRead, index: L.index, inFigma: L.inFigma, pending: L.pending, glossary: L.glossary },
  flows: manifest.flows.map((f) => ({ key: f.key, title: f.title, note: f.note || '',
    screens: f.steps.map((s) => ({ title: titleOf(s.screen), node: frameOf(s.screen) })) })),
  glossary: manifest.glossary || {},
};

const cover = `// generated by gen-docs.mjs — cover page in the house style
const DATA = ${JSON.stringify(DATA)};
const ST = DATA.style;
const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255 });
const FONT = { family: 'Inter', style: 'Regular' }, BOLD = { family: 'Inter', style: 'Semi Bold' };
await figma.loadFontAsync(FONT); await figma.loadFontAsync(BOLD);
const page = await figma.getNodeByIdAsync(DATA.page);
await figma.setCurrentPageAsync(page);
for (const c of [...page.children]) c.remove();
page.backgrounds = [{ type: 'SOLID', color: hex(ST.pageBg) }];
// documentation inks are fixed, never theme tokens: the theme's muted fails AA on the section gray
const INK = hex(ST.title), MUTED = hex(ST.subtle);
const text = (chars, size, bold, color, width) => {
  const t = figma.createText(); t.fontName = bold ? BOLD : FONT; t.characters = chars || ' '; t.fontSize = size;
  t.fills = [{ type: 'SOLID', color: color || INK }];
  if (width) { t.textAutoResize = 'HEIGHT'; t.resize(width, t.height); }
  return t;
};
const stack = (dir, name, gap) => { const f = figma.createAutoLayout(dir, { name, itemSpacing: gap }); f.fills = []; return f; };
const W = 1280;
const sec = figma.createSection(); page.appendChild(sec);
sec.name = DATA.text.section; sec.fills = [{ type: 'SOLID', color: hex(ST.sectionFill) }];
sec.setSharedPluginData('uic', 'cover', '1');
const head = stack('VERTICAL', 'header', 6);
head.appendChild(text(DATA.name, 40, true));
if (DATA.summary) head.appendChild(text(DATA.summary, 16, false, MUTED, W));
sec.appendChild(head); head.x = 80; head.y = 60;

const board = stack('VERTICAL', DATA.text.content, 40);
const facts = stack('HORIZONTAL', DATA.text.facts, 48);
for (const [k, v] of DATA.facts) { const c = stack('VERTICAL', k, 4); c.appendChild(text(k, 12, true, MUTED)); c.appendChild(text(v, 15, false)); facts.appendChild(c); }
board.appendChild(facts);
const pair = (k, v) => { const r = stack('HORIZONTAL', k, 24); r.appendChild(text(k, 15, true, null, 200)); r.appendChild(text(v, 15, false, MUTED, W - 224)); return r; };
board.appendChild(text(DATA.text.howToRead, 28, true));
for (const [k, v] of DATA.legend) board.appendChild(pair(k, v));

board.appendChild(text(DATA.text.index, 28, true));
let links = 0;
for (const f of DATA.flows) {
  const block = stack('VERTICAL', f.key + ' · ' + f.title, 6);
  block.appendChild(text(f.key + ' · ' + f.title + (f.note ? ' — ' + f.note : ''), 16, true, null, W));
  const line = f.screens.map((s, i) => (i + 1) + '. ' + s.title).join('   ');
  const t = text(line, 13, false, MUTED, W);
  // every screen in Figma links straight to its frame
  let at = 0;
  f.screens.forEach((s, i) => {
    const label = (i + 1) + '. ' + s.title;
    const start = line.indexOf(label, at); at = start + label.length;
    if (!s.node) return;
    t.setRangeHyperlink(start, start + label.length, { type: 'NODE', value: s.node });
    t.setRangeFills(start, start + label.length, [{ type: 'SOLID', color: INK }]);
    t.setRangeTextDecoration(start, start + label.length, 'UNDERLINE');
    links++;
  });
  block.appendChild(t);
  const done = f.screens.filter((s) => s.node).length;
  if (done < f.screens.length) block.appendChild(text(done ? DATA.text.inFigma.replace('{done}', done).replace('{n}', f.screens.length) : DATA.text.pending, 12, false, MUTED));
  board.appendChild(block);
}
const gl = Object.entries(DATA.glossary);
if (gl.length) { board.appendChild(text(DATA.text.glossary, 28, true)); for (const [k, v] of gl) board.appendChild(pair(k, v)); }
sec.appendChild(board); board.x = 80; board.y = Math.max(200, head.y + head.height + 64);
sec.resizeWithoutConstraints(Math.max(board.width, head.width) + 160, board.y + board.height + 80);
sec.x = 0; sec.y = 0;
return { cover: sec.id, flows: DATA.flows.length, links };
`;

writeFileSync(path.join(outDir, 'cover.figma.js'), cover);
console.log(JSON.stringify({ cover: cover.length, flows: DATA.flows.length, screens: Object.keys(state.screens).length }));
